set_property SRC_FILE_INFO {cfile:D:/FPGA/LAB03_HW/p2/p2.srcs/constrs_1/new/pynq-z2_v1.0.xdc rfile:../../../p2.srcs/constrs_1/new/pynq-z2_v1.0.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports { sw_tri_i[0] }]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M19 IOSTANDARD LVCMOS33} [get_ports { sw_tri_i[1] }]
