# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA/LAB02_HW/p1/block4/block4.srcs/sources_1/bd/design_1/ip/design_1_FSM_Decoder_0_0/design_1_FSM_Decoder_0_0.xci
# IP: The module: 'design_1_FSM_Decoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/LAB02_HW/p1/block4/block4.srcs/FPGA/LAB02_HW/p1/block1/block1.srcs/constrs_1/new/de_OOC.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FSM_Decoder_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/FPGA/LAB02_HW/p1/block4/block4.srcs/sources_1/bd/design_1/ip/design_1_FSM_Decoder_0_0/design_1_FSM_Decoder_0_0.xci
# IP: The module: 'design_1_FSM_Decoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA/LAB02_HW/p1/block4/block4.srcs/FPGA/LAB02_HW/p1/block1/block1.srcs/constrs_1/new/de_OOC.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_FSM_Decoder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
